version: '3'
services:

  redis:
    hostname: redis
    image: redis:latest
    ports:
      - "6379:6379"

  database:
    image: mysql:latest
    volumes:
      - ./database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mysql-password
      - MYSQL_DATABASE=colander
    ports:
      - "3306:3306"

  web:
    build:
      context: web
      dockerfile: Dockerfile.web
    volumes:
      - ./web:/web
    environment:
      - PORT=5000
      - FLASK_DEBUG=1
    ports:
      - "5000:5000"
    depends_on:
      - database
    env_file:
      - web/.env
