version: '3'
services:

  redis:
    hostname: redis
    image: redis:latest
    ports:
      - "6379:6379"

  database:
    image: mysql:latest
    volumes:
      - ./database:/var/lib/mysql
      - ./mysql-config:/etc/mysql/conf.d
    environment:
      - MYSQL_ROOT_PASSWORD=mysql-password
      - MYSQL_DATABASE=colander
    ports:
      - "3306:3306"

  web:
    build:
      context: web
      dockerfile: Dockerfile.web
    volumes:
      - ./web:/web
    environment:
      - PORT=5000
      - FLASK_DEBUG=1
    ports:
      - "5000:5000"
      - "5555:5555"
    depends_on:
      - database
    env_file:
      - web/.env

  spiders:
    build:
      context: spiders
      dockerfile: Dockerfile.spiders
    volumes:
      - ./spiders:/spiders
    hostname: spiders
    depends_on:
      - redis
      - database
    links:
      - redis
      - database
    environment:
      - SPIDERS_MAX_ITEMS=1000
      - DOWNLOAD_DELAY=0
    env_file:
      - ./web/.env
    ports:
      - "6800:6800"
    command: ["--help"]


