"""Added Vendor

Revision ID: 14551372d484
Revises: cf7fe4431c4a
Create Date: 2018-01-01 12:29:32.507804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14551372d484'
down_revision = 'cf7fe4431c4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('website', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendor_name'), 'vendor', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vendor_name'), table_name='vendor')
    op.drop_table('vendor')
    # ### end Alembic commands ###
