"""Added image_url to Vendor

Revision ID: b8beab72138b
Revises: f60e25ba5e0e
Create Date: 2018-01-01 18:59:30.500300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8beab72138b'
down_revision = 'f60e25ba5e0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendor', sa.Column('image_url', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendor', 'image_url')
    # ### end Alembic commands ###
