"""Modified Vendor indexes

Revision ID: f60e25ba5e0e
Revises: 14551372d484
Create Date: 2018-01-01 12:30:54.263123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f60e25ba5e0e'
down_revision = '14551372d484'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_vendor_website'), 'vendor', ['website'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vendor_website'), table_name='vendor')
    # ### end Alembic commands ###
