FROM python:latest
WORKDIR /web
ADD . /web
RUN pip install -r requirements.txt
RUN apt-get update && apt-get install -y supervisor
ENV PYTHONUNBUFFERED=0 PYTHONPATH=/web/lib/amazonmws

#ENTRYPOINT ["supervisord"]
CMD ["supervisord", "-c", "supervisord_worker.conf"]