FROM python:latest
COPY ../lib /lib
WORKDIR /web
ADD . /web
RUN pip install -r requirements.txt
RUN apt-get update && apt-get install -y supervisor
ENV PYTHONUNBUFFERED=1 PYTHONPATH=/lib FLASK_APP=colander.py
RUN useradd -m webuser
USER webuser

# Development:
ENTRYPOINT ["supervisord"]
CMD ["-c", "supervisord.conf"]
# TODO: Create separate conf files for web-only and worker-only modes

# Web only:
# ENTRYPOINT ["gunicorn"]
# CMD ["app:app"]

# Worker only:
# ENTRYPOINT ["supervisord"]
# CMD ["-c", "supervisord.conf"]