FROM python:latest
WORKDIR /web
ADD . /web
RUN pip install -r requirements.txt
ENV PYTHONUNBUFFERED=1 PYTHONPATH=/web/lib FLASK_APP=colander.py
RUN useradd -m webuser
USER webuser
# ENTRYPOINT ["gunicorn"]
# CMD ["app:app"]
ENTRYPOINT ["flask"]
CMD ["run", "-h", "0.0.0.0"]
