FROM python:latest
WORKDIR /web
ADD . /web
RUN pip install -r requirements.txt
RUN apt-get update && apt-get install -y supervisor
ENV PYTHONUNBUFFERED=1 PYTHONPATH=/web/lib/amazonmws FLASK_APP=colander.py

# Development:
# ENTRYPOINT ["flask"]
# CMD ["run", "-h", "0.0.0.0"]

# Web only:
# ENTRYPOINT ["gunicorn"]
# CMD ["app:app"]

# Supervisor:
#ENTRYPOINT ["supervisord"]
CMD ["supervisord", "-c", "supervisord_web.conf"]